package com.laidu.bishe.wechat.mapper;

import com.laidu.bishe.wechat.domain.CheckinDetailInfo;

public interface CheckinDetailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkinDetailInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int insert(CheckinDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkinDetailInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int insertSelective(CheckinDetailInfo record);
}