package com.laidu.bishe.wechat.mapper;

import com.laidu.bishe.wechat.domain.CourseInfo;

public interface CourseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int deleteByPrimaryKey(Object courseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int insert(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int insertSelective(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    CourseInfo selectByPrimaryKey(Object courseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int updateByPrimaryKeySelective(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int updateByPrimaryKey(CourseInfo record);
}