package com.laidu.bishe.wechat.mapper;

import com.laidu.bishe.wechat.domain.StudentInfo;

public interface StudentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int deleteByPrimaryKey(Long stuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int insert(StudentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int insertSelective(StudentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    StudentInfo selectByPrimaryKey(Long stuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int updateByPrimaryKeySelective(StudentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int updateByPrimaryKey(StudentInfo record);
}