package com.laidu.bishe.wechat.mapper;

import com.laidu.bishe.wechat.domain.TeacherInfo;

public interface TeacherInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int deleteByPrimaryKey(Object teacherid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int insert(TeacherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int insertSelective(TeacherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    TeacherInfo selectByPrimaryKey(Object teacherid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int updateByPrimaryKeySelective(TeacherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherInfo
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    int updateByPrimaryKey(TeacherInfo record);
}