package com.laidu.bishe.wechat.domain;

import java.util.Date;

public class CheckinDetailInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkinDetailInfo.stuID
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    private Object stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkinDetailInfo.checkinTime
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    private Date checkintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkinDetailInfo.proofPath
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    private String proofpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkinDetailInfo.checkinType
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    private Short checkintype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkinDetailInfo.isSucc
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    private Boolean issucc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkinDetailInfo.checkinResult
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    private Short checkinresult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkinDetailInfo.stuID
     *
     * @return the value of checkinDetailInfo.stuID
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public Object getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkinDetailInfo.stuID
     *
     * @param stuid the value for checkinDetailInfo.stuID
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public void setStuid(Object stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkinDetailInfo.checkinTime
     *
     * @return the value of checkinDetailInfo.checkinTime
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public Date getCheckintime() {
        return checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkinDetailInfo.checkinTime
     *
     * @param checkintime the value for checkinDetailInfo.checkinTime
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public void setCheckintime(Date checkintime) {
        this.checkintime = checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkinDetailInfo.proofPath
     *
     * @return the value of checkinDetailInfo.proofPath
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public String getProofpath() {
        return proofpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkinDetailInfo.proofPath
     *
     * @param proofpath the value for checkinDetailInfo.proofPath
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public void setProofpath(String proofpath) {
        this.proofpath = proofpath == null ? null : proofpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkinDetailInfo.checkinType
     *
     * @return the value of checkinDetailInfo.checkinType
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public Short getCheckintype() {
        return checkintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkinDetailInfo.checkinType
     *
     * @param checkintype the value for checkinDetailInfo.checkinType
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public void setCheckintype(Short checkintype) {
        this.checkintype = checkintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkinDetailInfo.isSucc
     *
     * @return the value of checkinDetailInfo.isSucc
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public Boolean getIssucc() {
        return issucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkinDetailInfo.isSucc
     *
     * @param issucc the value for checkinDetailInfo.isSucc
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public void setIssucc(Boolean issucc) {
        this.issucc = issucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkinDetailInfo.checkinResult
     *
     * @return the value of checkinDetailInfo.checkinResult
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public Short getCheckinresult() {
        return checkinresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkinDetailInfo.checkinResult
     *
     * @param checkinresult the value for checkinDetailInfo.checkinResult
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public void setCheckinresult(Short checkinresult) {
        this.checkinresult = checkinresult;
    }
}