package com.laidu.bishe.wechat.domain;

import java.util.Date;

public class SeqInfo extends SeqInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seqInfo.seqID
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    private Integer seqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seqInfo.startTime
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    private Date starttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seqInfo.seqID
     *
     * @return the value of seqInfo.seqID
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public Integer getSeqid() {
        return seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seqInfo.seqID
     *
     * @param seqid the value for seqInfo.seqID
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public void setSeqid(Integer seqid) {
        this.seqid = seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seqInfo.startTime
     *
     * @return the value of seqInfo.startTime
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seqInfo.startTime
     *
     * @param starttime the value for seqInfo.startTime
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }
}