package com.laidu.bishe.wechat.domain;

public class SeqInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seqInfo.teacherID
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    private Object teacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seqInfo.courseID
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    private Object courseid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seqInfo.teacherID
     *
     * @return the value of seqInfo.teacherID
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public Object getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seqInfo.teacherID
     *
     * @param teacherid the value for seqInfo.teacherID
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public void setTeacherid(Object teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seqInfo.courseID
     *
     * @return the value of seqInfo.courseID
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public Object getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seqInfo.courseID
     *
     * @param courseid the value for seqInfo.courseID
     *
     * @mbg.generated Mon May 08 16:09:59 CST 2017
     */
    public void setCourseid(Object courseid) {
        this.courseid = courseid;
    }
}